Suppress grep error

diff --git a/conan_linuxmac_build/action.yml b/conan_linuxmac_build/action.yml
--- a/conan_linuxmac_build/action.yml
+++ b/conan_linuxmac_build/action.yml
@@ -87,9 +87,14 @@ runs:
         path: github-actions
         fetch-depth: 1
 
+# Continue on error is to suppress grep 
+# exit code when compatibility is not present
     - name: Make compatibility profile (if needed) 
+      continue-on-error: true
       run: |
         python github-actions/python/get_compatibility_list.py ${{ inputs.conan-build-os }} ${{ inputs.conan-compiler }} ${{ inputs.conan-compiler-version }}
+        compatibility_found=`conan profile list | (grep -E 'compatibility' || true)`
+        echo "compatibility_found=$compatibility_found" >> $GITHUB_ENV
       shell: bash
 
     - name: Build with conan 
@@ -110,7 +115,6 @@ runs:
         mkdir _build
         if [ -d "./external/conan-recipes" ]; then conan export ./external/conan-recipes/bundle_package bundleutils/0.1@lkeb/stable; fi
         
-        compatibility_found=`conan profile list | (grep -E 'compatibility' || true)`
         if [[ $compatibility_found == compatibility ]]; then
           conan create . lkeb/stable  -pr:b=action_build -pr:h=action_build -pr compatibility
         else
